[build]
  base = "."
  publish = "client/dist"
  command = "cd client && npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
